alias: Bel uit
initial_state: on
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '20:00:01'
condition:
  condition: time
  after: '20:00:00'
  before: '07:00:00'
action:
  service: switch.turn_off
  data:
    entity_id: switch.gang_deurbel_chime_enabled
