reboot:
  name: Reboot device
  target:
    device:
      integration: openwrt
exec:
  name: Execute command
  target:
    device:
      integration: openwrt
  fields:
    command:
      name: Command
      description: Command to execute
      required: true
      example: "wifi reload"
      selector:
        text: {}
    arguments:
      name: Command arguments
      description: Arguments to append to the command (one per line)
      required: false
      selector:
        text:
          multiline: true
    environment:
      name: Environment variables
      description: Map of Environment variables names with values
      required: false
      selector:
        object: {}
    extra:
      name: Extra event fields
      description: Arbitrary object added to the execute result event
      required: false
      selector:
        object: {}
init:
  name: Managing services
  target:
    device:
      integration: openwrt
  fields:
    name:
      name: Name
      description: Service Name
      required: true
      example: "dnsmasq"
      selector:
        text: {}
    action:
      name: Action
      description: Common actions supported by most services
      required: true
      example: "restart"
      default: "restart"
      selector:
        select:
          options:
            - "start"
            - "stop"
            - "restart"
            - "reload"
            - "enable"
            - "disable"
ubus:
  name: Make arbitrary Ubus call
  target:
    device:
      integration: openwrt
  fields:
    subsystem:
      name: Ubus sub-system
      description: Top-level Ubus sub-system 
      required: true
      example: "system"
      selector:
        text: {}
    method:
      name: Ubus method
      description: Ubus method to call 
      required: true
      example: "board"
      selector:
        text: {}
    parameters:
      name: Call parameters
      description: Ubus call paramteres
      required: false
      selector:
        object: {}
