---
# Wemos D1 mini module
#
# Can be found in various Tuya-based devices.
#
# https://docs.platformio.org/en/latest/boards/espressif8266/esp8285.html
#
esphome:
  <<: !include .esphome.yaml

esp8266:
  board: d1_mini
  framework:
    version: recommended
