clear_cache:
  name: Clear Cache
  description: Remove text-to-speech cache files from Chime TTS and/or Home Assistant.
  fields:
    clear_chimes_cache:
      default: true
      description: Remove the cached local chime files downloaded by Chime TTS
      example: 'True'
      name: Temporary Chimes Cache
      required: false
      selector:
        boolean: null
    clear_ha_tts_cache:
      name: Home Assistant TTS Cache
      description: Remove the TTS audio files stored in the Home Assistant TTS cache
      default: true
      example: 'True'
      required: false
      selector:
        boolean: null
    clear_temp_tts_cache:
      default: true
      description: Remove the local temporary audio files stored in the Chime TTS
        cache
      example: 'True'
      name: Temporary Chime TTS Cache
      required: false
      selector:
        boolean: null
    clear_www_tts_cache:
      default: true
      description: Remove the publicly accessible audio files stored in the Chime
        TTS cache
      example: 'True'
      name: Publicly Accessible Chime TTS Cache
      required: false
      selector:
        boolean: null
replay:
  name: Replay
  description: Replay the last service call to chime_tts.say with the same parameters
say:
  name: Say
  description: Play an audio file before TTS audio
  target:
    entity:
      domain: media_player
      supported_features:
      - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
  fields:
    chime_path:
      description: A preset or custom audio file to be played before TTS audio
      example: custom_components/chime_tts/mp3s/bells.mp3
      name: Chime Path
      required: false
      selector:
        select:
          custom_value: true
          mode: dropdown
          multiple: false
          options: []
          translation_key: chime_paths
    end_chime_path:
      description: A preset or custom audio file to be played after TTS audio
      example: custom_components/chime_tts/mp3s/tada.mp3
      name: End Chime Path
      required: false
      selector:
        select:
          custom_value: true
          mode: dropdown
          multiple: false
          options: []
          translation_key: chime_paths
    offset:
      description: Adds a delay between audio segments when value > 0, or overlays
        audio segments when value < 0.
      example: 450
      name: Offset
      required: false
      selector:
        number:
          max: 10000
          min: -10000
          mode: box
          step: 10
          unit_of_measurement: ms
    crossfade:
      description: Crossfade (in milliseconds) between audio segments
      example: 1000
      name: Crossfade
      required: false
      selector:
        number:
          min: 0
          mode: box
          step: 1
          unit_of_measurement: ms
    final_delay:
      description: Final delay (in milliseconds) added to the end of the audio
      example: 100
      name: Final Delay
      required: false
      selector:
        number:
          max: 10000
          min: 0
          mode: box
          step: 1
          unit_of_measurement: ms
    message:
      description: Text converted into TTS audio
      example: Hello world!
      name: Message
      required: false
      selector:
        template: null
    tts_platform:
      description: TTS platform used to generate TTS audio
      example: google_translate
      name: TTS Platform
      required: false
      selector:
        select:
          custom_value: true
          mode: dropdown
          multiple: false
          options:
          - label: Amazon Polly
            value: amazon_polly
          - label: Baidu
            value: baidu
          - label: ElevenLabs
            value: tts.elevenlabs
          - label: Google Cloud
            value: google_cloud
          - label: Google Translate
            value: google_translate
          - label: IBM Watson TTS
            value: watson_tts
          - label: MaryTTS
            value: marytts
          - label: Microsoft Edge TTS
            value: edge_tts
          - label: Microsoft Text-to-Speech (TTS)
            value: microsoft
          - label: Nabu Casa Cloud TTS
            value: cloud
          - label: OpenAI TTS
            value: openai_tts
          - label: Pico TTS
            value: picotts
          - label: Piper
            value: tts.piper
          - label: VoiceRSS
            value: voicerss
          - label: Yandex TTS
            value: yandextts
    tts_speed:
      description: Set the speed of the TTS audio to between 1% and 500% of the original
      example: 125
      name: TTS Speed
      required: false
      selector:
        number:
          max: 500
          min: 1
          mode: slider
          step: 5
          unit_of_measurement: '%'
    tts_pitch:
      description: Change the the TTS pitch in semitones. Negative values for lower,
        positive for higher
      example: 3
      name: TTS Pitch
      required: false
      selector:
        number:
          max: 100
          min: -100
          mode: slider
          step: 1
          unit_of_measurement: semitones
    volume_level:
      description: The volume to use when playing audio
      example: 0.75
      name: Volume Level
      required: false
      selector:
        number:
          max: 1.0
          min: 0.0
          mode: slider
          step: 0.01
    join_players:
      description: Join media_players for simultaneous playback (for supported speakers)
      example: 'True'
      name: Join Players
      required: false
      selector:
        boolean: null
    unjoin_players:
      description: Release the joined media_players after playback
      example: 'True'
      name: Unjoin Players
      required: false
      selector:
        boolean: null
    cache:
      description: Whether or not to save/reuse the generated audio file in a local
        cache
      example: 'True'
      name: Cache
      required: false
      selector:
        boolean: null
    announce:
      description: Reduce volume of currently playing audio during during announcement
        (on supported devices)
      example: 'True'
      name: Announce
      required: false
      selector:
        boolean: null
    fade_audio:
      description: Fade out playing audio during announcement, fade back in when completed
        (on supported devices)
      example: 'True'
      name: Fade Audio
      required: false
      selector:
        boolean: null
    audio_conversion:
      description: Convert the audio to match Alexa speaker requirements, or use your
        own FFmpeg arguments
      example: Alexa
      name: Audio Conversion
      required: false
      selector:
        select:
          custom_value: true
          options:
          - label: Alexa
            value: Alexa
          - label: 'Volume x% (replace this text, eg: "Volume 125%")'
            value: Volume 100%
          - label: Custom (replace this text with your FFmpeg arguments)
            value: Custom
          translation_key: audio_conversion
    language:
      description: The TTS language (supported by Google Translate, Microsoft Edge
        TTS, Amazon Polly and Nabu Casa Cloud TTS)
      example: en
      name: Language
      required: false
      selector:
        text: null
    tld:
      description: The dialect (supported by Google Translate)
      example: com.au
      name: TLD
      required: false
      selector:
        select:
          options:
          - label: com
            value: com
          - label: co.uk
            value: co.uk
          - label: com.au
            value: com.au
          - label: ca
            value: ca
          - label: co.in
            value: co.in
          - label: ie
            value: ie
          - label: co.za
            value: co.za
          - label: fr
            value: fr
          - label: com.br
            value: com.br
          - label: pt
            value: pt
          - label: es
            value: es
    voice:
      description: Define the voice for the TTS audio (on supported TTS platforms)
      example: en-AU
      name: Voice
      required: false
      selector:
        text: null
    options:
      description: YAML Options to pass to TTS services (will override `tld` and `voice`
        fields)
      example: "tld: com.au\voice: en-AU"
      name: Options
      required: false
      selector:
        text:
          multiline: true
say_url:
  name: Say URL
  description: Generates an audio file with the `chime_tts.say` service and returns
    either an external URL or a local file path, depending on the folder set in the
    configuration
  fields:
    chime_path:
      description: A preset or custom audio file to be played before TTS audio
      example: custom_components/chime_tts/mp3s/bells.mp3
      name: Chime Path
      required: false
      selector:
        select:
          custom_value: true
          mode: dropdown
          multiple: false
          options: []
          translation_key: chime_paths
    end_chime_path:
      description: A preset or custom audio file to be played after TTS audio
      example: custom_components/chime_tts/mp3s/tada.mp3
      name: End Chime Path
      required: false
      selector:
        select:
          custom_value: true
          mode: dropdown
          multiple: false
          options: []
          translation_key: chime_paths
    offset:
      description: Adds a delay between audio segments when value > 0, or overlays
        audio segments when value < 0.
      example: 450
      name: Offset
      required: false
      selector:
        number:
          max: 10000
          min: -10000
          mode: box
          step: 10
          unit_of_measurement: ms
    crossfade:
      description: Crossfade (in milliseconds) between audio segments
      example: 1000
      name: Crossfade
      required: false
      selector:
        number:
          min: 0
          mode: box
          step: 1
          unit_of_measurement: ms
    final_delay:
      description: Final delay (in milliseconds) added to the end of the audio
      example: 100
      name: Final Delay
      required: false
      selector:
        number:
          max: 10000
          min: 0
          mode: box
          step: 1
          unit_of_measurement: ms
    message:
      description: Text converted into TTS audio
      example: Hello world!
      name: Message
      required: false
      selector:
        template: null
    tts_platform:
      description: TTS platform used to generate TTS audio
      example: google_translate
      name: TTS Platform
      required: false
      selector:
        select:
          custom_value: true
          mode: dropdown
          multiple: false
          options:
          - label: Amazon Polly
            value: amazon_polly
          - label: Baidu
            value: baidu
          - label: ElevenLabs
            value: tts.elevenlabs
          - label: Google Cloud
            value: google_cloud
          - label: Google Translate
            value: google_translate
          - label: IBM Watson TTS
            value: watson_tts
          - label: MaryTTS
            value: marytts
          - label: Microsoft Edge TTS
            value: edge_tts
          - label: Microsoft Text-to-Speech (TTS)
            value: microsoft
          - label: Nabu Casa Cloud TTS
            value: cloud
          - label: OpenAI TTS
            value: openai_tts
          - label: Pico TTS
            value: picotts
          - label: Piper
            value: tts.piper
          - label: VoiceRSS
            value: voicerss
          - label: Yandex TTS
            value: yandextts
    tts_speed:
      description: Set the speed of the TTS audio to between 1% and 500% of the original
      example: 125
      name: TTS Speed
      required: false
      selector:
        number:
          max: 500
          min: 1
          mode: slider
          step: 5
          unit_of_measurement: '%'
    tts_pitch:
      description: Change the the TTS pitch in semitones. Negative values for lower,
        positive for higher
      example: 3
      name: TTS Pitch
      required: false
      selector:
        number:
          max: 100
          min: -100
          mode: slider
          step: 1
          unit_of_measurement: semitones
    cache:
      description: Whether or not to save/reuse the generated audio file in a local
        cache
      example: 'True'
      name: Cache
      required: false
      selector:
        boolean: null
    audio_conversion:
      description: Convert the audio to match Alexa speaker requirements, or use your
        own FFmpeg arguments
      example: Alexa
      name: Audio Conversion
      required: false
      selector:
        select:
          custom_value: true
          options:
          - label: Alexa
            value: Alexa
          - label: 'Volume x% (replace this text, eg: "Volume 125%")'
            value: Volume 100%
          - label: Custom (replace this text with your FFmpeg arguments)
            value: Custom
          translation_key: audio_conversion
    language:
      description: The TTS language (supported by Google Translate, Microsoft Edge
        TTS and Nabu Casa Cloud TTS)
      example: en
      name: Language
      required: false
      selector:
        text: null
    tld:
      description: The dialect (supported by Google Translate)
      example: com.au
      name: TLD
      required: false
      selector:
        select:
          options:
          - label: com
            value: com
          - label: co.uk
            value: co.uk
          - label: com.au
            value: com.au
          - label: ca
            value: ca
          - label: co.in
            value: co.in
          - label: ie
            value: ie
          - label: co.za
            value: co.za
          - label: fr
            value: fr
          - label: com.br
            value: com.br
          - label: pt
            value: pt
          - label: es
            value: es
    voice:
      description: Define the voice for the TTS audio (on supported TTS platforms)
      example: en-AU
      name: Voice
      required: false
      selector:
        text: null
    options:
      description: YAML Options to pass to TTS services (will override `tld` and `voice`
        fields)
      example: "tld: com.au\voice: en-AU"
      name: Options
      required: false
      selector:
        text:
          multiline: true
