################################################
## Integrations / Automations
## Verwijst naar automations.yaml met alle automatiseringsregels
################################################
automation: !include ../automations.yaml
