################################################
## Integrations / Home Assistant
## Aanpassingen van entity namen, iconen en domeinen via customize_glob
################################################
homeassistant:
  # Aanpassingen op basis van patronen (iconen, device classes, verbergen)
  customize_glob: !include_dir_merge_named ../customizations/globs
