language: python
python:
  - "3.7.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev
  - sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
  - touch home-assistant_v2.db
  - touch home-assistant.log
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config