- id: '1607379994170'
  alias: WC lampen aan bij beweging
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 120
      motion_entity: binary_sensor.wc_bewegingssensor
      light_target:
        entity_id: light.wc_plafond
- id: '1608038011592'
  alias: Symfonisk lampen Noa
  description: ''
  use_blueprint:
    path: deconz_ikea_symfonisk_lights.yaml
    input:
      brightness: 50
      light:
        entity_id: light.noa_bed
      double_press:
      - service: light.turn_on
        target:
          device_id: cda7501a0b9811ebac43cb81d1a09be0
        data:
          effect: '{{ state_attr(''light.noa_bed'', ''effect_list'') | random }}'
      triple_press:
      - service: select.select_option
        target:
          entity_id: select.wled_noa_preset
        data:
          option: Solid white
      remote: b225a6d4ec52c665162a23c382f2f38f
- id: '1617684358026'
  alias: Home Assistant Update Notification for Android
  description: ''
  use_blueprint:
    path: fortepc/update-notif-for-android.yaml
    input:
      clickAction: https://my.home-assistant.io/redirect/supervisor/
      delay: 0
      notify_device: 267251cf143411ebbf4ef5c3186f709c
      notification_message: Home Assistant {{ newest_version }} is beschikbaar
      group: Available Updates
- id: '1620411227739'
  alias: Notificatie wanneer DSMR niet updated
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dsmr_reading_timestamp
    for: 00:10:00
  condition: []
  action:
  - service: notify.mobile_app_telefoon_rudolf
    data:
      title: DSMR wordt niet geupdated!
      message: Check of de USB binding nog goed staat in de VM.
  mode: single
- id: '1624693593116'
  alias: Thermostaat nachtstand
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.thermostaat
  mode: single
- id: '1624693689373'
  alias: Afval
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.afvalinfo_tomorrow
      state: none
  action:
  - service: notify.family
    data_template:
      title: Morgen is een afvaldag
      message: 'Opgehaalde afval: {{ states.sensor.afvalinfo_tomorrow.state }}'
  initial_state: true
- id: '1624693815080'
  alias: Laatste gaat naar bed
  trigger:
  - platform: state
    entity_id: input_boolean.nachtmode
    from: 'off'
    to: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id: script.last_sleeper
  initial_state: true
  mode: single
- id: '1624693857334'
  alias: Nachtverlichting buiten
  description: Handle night lights based on illumination
  trigger:
  - platform: state
    entity_id: binary_sensor.donker_buiten
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.donker_buiten
        state: 'on'
      sequence:
      - service: light.turn_on
        entity_id: light.buitenverlichting
    - conditions:
      - condition: state
        entity_id: binary_sensor.donker_buiten
        state: 'off'
      sequence:
      - service: light.turn_off
        entity_id: light.buitenverlichting
  initial_state: true
- id: '1624693897568'
  alias: Ramen boven staan nog open
  trigger:
  - platform: state
    entity_id: group.parents
    to: home
  - platform: time
    at: '16:00:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '16:00:00'
      before: '20:00:00'
    - condition: state
      entity_id: group.parents
      state: home
    - condition: state
      entity_id: group.ramen_boven
      state: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.rudolf
        state: home
      sequence:
      - service: notify.mobile_app_telefoon_rudolf
        data:
          title: Er staan nog ramen open
          message: '{{ message_data }}'
          data:
            ttl: 0
            priority: high
    - conditions:
      - condition: state
        entity_id: person.leny
        state: home
      sequence:
      - service: notify.mobile_app_telefoon_leny
        data:
          title: Er staan nog ramen open
          message: '{{ message_data }}'
          data:
            ttl: 0
            priority: high
  variables:
    message_data: "{% for entity_id in states.group.ramen_boven.attributes.entity_id\
      \ -%}\n  {% if(states(entity_id) == 'on')-%}\n      {{- '\\n' -}}\n    - {%\
      \ print(state_attr(entity_id,'friendly_name')) | regex_replace(find='Raam',\
      \ replace='', ignorecase=False)-%}\n  {% endif-%}\n{%- endfor %}"
- id: '1624693921089'
  alias: Takken
  trigger:
  - platform: time
    at: 09:00:00
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.afval_info_days_until_takken
      below: 8
    - condition: time
      weekday:
      - fri
  action:
  - service: notify.family
    data_template:
      title: Takken worden binnenkort opghaald
      message: 'Ophaaldatum: {{ states.sensor.afvalinfo_takken.state }}'
  initial_state: true
- id: '1629894664286'
  alias: Achtertuinverlichting aan
  trigger:
  - platform: time
    at: 07:00
  condition:
  - condition: state
    entity_id: binary_sensor.donker_buiten
    state: 'on'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.achtertuin_lantaarnpaal
  initial_state: true
  mode: single
- id: '1629894698473'
  alias: Achtertuin verlichting 's nachts uit
  description: '''s nachts na 10 minuten achtertuinverlichting uit.'
  trigger:
  - platform: state
    entity_id: light.achtertuin_lantaarnpaal
    to: 'on'
    for: 0:10:00
  condition:
  - condition: time
    after: 00:00
    before: 07:00
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.kleine_schuur_lantaarnpaal
  mode: single
- id: '1629894738043'
  alias: Achtertuinverlichting uit
  trigger:
  - platform: time
    at: 00:00
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.achtertuin_lantaarnpaal
  initial_state: true
  mode: single
- id: '1629895298921'
  alias: Bel aan
  trigger:
  - platform: time
    at: 07:00
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: 07:00:00
    before: '20:00'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.gang_bel_enabled
  initial_state: true
  mode: single
- id: '1629895322152'
  alias: Bel uit
  trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '20:00'
  condition:
  - condition: time
    after: '20:00'
    before: 07:00
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.gang_bel_enabled
  initial_state: true
  mode: single
- id: '1629895350290'
  alias: Zolder schakelaar
  trigger:
  - platform: state
    entity_id: binary_sensor.zolder_schakelaar
    from: on,off
    to: on,off
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.zolder_plafond
  mode: single
- id: '1629911279530'
  alias: Bijkeuken - Licht aan
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_bewegingssensor
    to: 'on'
  - platform: state
    entity_id: binary_sensor.donker_binnen
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.donker_binnen
    state: 'on'
  - condition: state
    entity_id: binary_sensor.bijkeuken_bewegingssensor
    state: 'on'
  action:
  - type: turn_on
    device_id: 8dafd02b71a94a0f80376693ac7132ea
    entity_id: light.bijkeuken_plafond
    domain: light
  mode: single
- id: '1629911528869'
  alias: Bijkeuken - Licht uit
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_bewegingssensor
    to: 'off'
    for: 00:01:00
  - platform: state
    entity_id: binary_sensor.donker_binnen
    to: 'off'
  condition:
  - condition: state
    entity_id: light.bijkeuken_plafond
    state: 'on'
  action:
  - type: turn_off
    device_id: 8dafd02b71a94a0f80376693ac7132ea
    entity_id: light.bijkeuken_plafond
    domain: light
  mode: single
- id: '1631009095968'
  alias: Notificatie ramen zolder open
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition:
  - condition: state
    entity_id: binary_sensor.zolder_raam_achter
    state: 'on'
  action:
  - service: notify.mobile_app_telefoon_rudolf
    data:
      message: Dus dicht doen makker!
      title: Het zolderraam staat nog open
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
        importance: high
  mode: single
- id: '1631707602352'
  alias: Tag Pasje is gescand
  description: ''
  trigger:
  - platform: tag
    tag_id: 53-BA-DF-2B
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.zolder_plafond
  mode: single
- id: '1632223302457'
  alias: Bewegingssensor schuur automatisch uit
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.kleine_schuur_bewegingssensor
    to: 'on'
    for:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: tele/rf_schuur/RESULT
      payload: '{"RfReceived":{"Data":"D2242E-off"}}'
  mode: single
- id: '1632469998878'
  alias: Wall tablet - Screen auto off
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wall_tablet_motion
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 15
    entity_id: light.lenovo_tab_m10_screen
  - platform: time
    at: '23:00'
  condition:
  - condition: state
    entity_id: binary_sensor.wall_tablet_motion
    state: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  action:
  - choose:
    - conditions:
      - condition: time
        after: '23:00'
        before: 07:00
      sequence:
      - service: light.turn_on
        data:
          transition: 5
          brightness: 1
        target:
          device_id: 4e5e759c521f542921a9c9132a2885b4
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: light.turn_off
        data: {}
        target:
          device_id: 4e5e759c521f542921a9c9132a2885b4
    default:
    - service: light.turn_on
      data:
        brightness: 1
      target:
        device_id: 4e5e759c521f542921a9c9132a2885b4
  mode: restart
- id: '1632471920007'
  alias: Wall tablet - Bright on motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wall_tablet_motion
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 100
    target:
      device_id: 4e5e759c521f542921a9c9132a2885b4
  mode: single
- id: '1632481170491'
  alias: Voortuin verlichting 's nachts
  description: Wanneer het donker is, lampen hek na 10 minuten weer aan.
  trigger:
  - platform: state
    entity_id: light.voortuin_hek
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: binary_sensor.donker_buiten
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.voortuin_hek
  mode: single
- id: '1632481269015'
  alias: Achterdeur open in het donker
  description: Wijzig verlichting wanneer achterdeur open gaat
  trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_deur
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.donker_buiten
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.achtertuin_lantaarnpaal
  - service: light.turn_off
    entity_id: light.voortuin_hek
  mode: single
- id: '1634330478124'
  alias: Bel gaat - Stuur bericht
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      notification_message: Er staat iemand voor de deur
      motion_sensor: binary_sensor.gang_bel_button
      camera: camera.voortuin
      notify_device: 267251cf143411ebbf4ef5c3186f709c
      delay: 0
      notification_title: Er wordt aangebeld
- id: '1634941186819'
  alias: Bel gaat - Toon pop-up
  description: Toont camerabeeld in popup wanneer bel gaat
  trigger:
  - platform: state
    entity_id: binary_sensor.gang_bel_button
    to: 'on'
  - platform: state
    entity_id: binary_sensor.voortuin_deurbel
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      device_id: 4e5e759c521f542921a9c9132a2885b4
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: browser_mod.popup
    data:
      title: Popup example
      card:
        type: custom:webrtc-camera
        entity: camera.voortuin
      deviceID:
      - ea5c0b48-bbd900ef
      hide_header: true
      large: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: browser_mod.close_popup
  mode: single
- id: '1636220861020'
  alias: Alarm wanneer weg
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_bewegingssensor
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bijkeuken_deur
    to: 'on'
  - platform: state
    entity_id: binary_sensor.woonkamer_raam
    to: 'on'
  - platform: state
    entity_id: binary_sensor.keuken_raam
    to: 'on'
  - platform: state
    entity_id: binary_sensor.mika_raam
    to: 'on'
  - platform: state
    entity_id: binary_sensor.noa_raam
    to: 'on'
  - platform: state
    entity_id: binary_sensor.slaapkamer_raam
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.home_alarm
  mode: single
- id: '1637959661190'
  alias: Deurbel automatisch uit
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.voortuin_deurbel
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: tele/rfbridge_meterkast/RESULT
      payload: '{"RfRaw":{"Data":"AA B1 03 044C 0172 16D0 080909090909090918091809090918181818
        55-off"}}'
  mode: single
- id: '1641238347569'
  alias: Boodschappen
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.shopping_list_contents
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.shopping_list_contents
    attribute: list_content
  - platform: state
    entity_id: person.rudolf
    to: WC De Vrijheid
  - platform: state
    entity_id: person.leny
    to: WC De Vrijheid
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.shopping_list_contents
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: person.leny
        state: WC De Vrijheid
      - condition: state
        entity_id: person.rudolf
        state: WC De Vrijheid
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.leny
        state: WC De Vrijheid
      sequence:
      - service: notify.mobile_app_telefoon_leny
        data:
          title: Er staan boodschappen op de lijst
          message: '{{ state_attr(''binary_sensor.shopping_list_contents'', ''list_content'')
            }}'
    - conditions:
      - condition: state
        entity_id: person.rudolf
        state: wc_de_vrijheid
      sequence:
      - service: notify.mobile_app_telefoon_rudolf
        data:
          title: Er staan boodschappen op de lijst
          message: '{{ state_attr(''binary_sensor.shopping_list_contents'', ''list_content'')
            }}'
    default: []
  mode: single
