- id: '1607379994170'
  alias: WC lampen aan bij beweging
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 120
      motion_entity: binary_sensor.wc_bewegingssensor
      light_target:
        entity_id: light.wc_plafond
- id: '1608038011592'
  alias: Symfonisk lampen Noa
  description: ''
  use_blueprint:
    path: deconz_ikea_symfonisk_lights.yaml
    input:
      brightness: '50'
      remote: b225a6d4ec52c665162a23c382f2f38f
      light:
        entity_id: light.noa_bed
      double_press:
      - service: input_select.select_next
        data: {}
        entity_id: input_select.noa_bed_effects
      triple_press:
      - service: input_select.select_option
        data:
          option: Solid
        entity_id: input_select.noa_bed_effects
- id: '1609882168905'
  alias: Mi Magic Cube
  description: ''
  use_blueprint:
    path: bergstrom/mi-magic-cube-deconz-45-actions.yaml
    input:
      remote: d0ff81b35fb174f03df700524e4dc25c
      cube_shake:
      - service: light.toggle
        data: {}
        entity_id: light.woonkamer_dressoir
      one_side_slide: false
      cube_one_side_slide: []
      cube_fall:
      - type: flash
        device_id: 3a2745d145a34069b819b8928a7ca82b
        entity_id: light.woonkamer_dressoir
        domain: light
- id: '1617684358026'
  alias: Home Assistant Update Notification for Android
  description: ''
  use_blueprint:
    path: fortepc/update-notif-for-android.yaml
    input:
      clickAction: https://my.home-assistant.io/redirect/supervisor/
      delay: 0
      notify_device: 267251cf143411ebbf4ef5c3186f709c
      notification_message: Home Assistant {{ newest_version }} is beschikbaar
      group: Available Updates
- id: '1617879450516'
  alias: Bijkeuken Lamp aan
  description: De lamp in de bijkeuken gaat aan bij beweging als het donker is binnen
  trigger:
  - platform: state
    entity_id: light.bijkeuken_plafond
    to: 'on'
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  condition:
  - condition: state
    entity_id: light.bijkeuken_plafond
    state: 'on'
  action:
  - service: timer.start
    data:
      duration: 00:01:35
    target:
      entity_id: timer.bijkeuken_beweging
  mode: single
- id: '1617880160430'
  alias: Bijkeuken Lamp automatisch uit
  description: De lamp in de bijkeuken moet na ingestelde tijd uitgaan
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bijkeuken_beweging
  condition:
  - condition: state
    entity_id: light.bijkeuken_plafond
    state: 'on'
  action:
  - service: light.turn_off
    target:
      entity_id: light.bijkeuken_plafond
  mode: single
- id: '1619442974401'
  alias: Bel gaat
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.gang_deurbel_button
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /media/snapshots/snapshot.jpg
    target:
      device_id: bab1e93d08ca11eba583dba8001b4553
  - service: notify.family
    data:
      message: Er staat iemand aan de voordeur
      title: De bel gaat
      data:
        image: /media/local/snapshots/snapshot.jpg
        ttl: 0
        priority: high
        clickAction: /lovelace-camera/voordeur
  mode: single
- id: '1619731156101'
  alias: Bijkeuken Beweging
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_bewegingssensor
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.donker_binnen
    state: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id: light.bijkeuken_plafond
  - condition: state
    entity_id: timer.bijkeuken_beweging
    state: active
  - service: timer.start
    data: {}
    target:
      entity_id: timer.bijkeuken_beweging
  mode: single
- id: '1620411227739'
  alias: Notificatie wanneer DSMR niet updated
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dsmr_reading_timestamp
    for: 00:10:00
  condition: []
  action:
  - service: notify.mobile_app_telefoon_rudolf
    data:
      title: DSMR wordt niet geupdated!
      message: Check of de USB binding nog goed staat in de VM.
  mode: single
