kiosk_mode:
  kiosk: false
  user_settings:
    - users:
        - tablet
      kiosk: true
button_card_templates: !include lovelace/button_card_templates.yaml
views:
  - type: custom:grid-layout
    theme: tablet
    path: 0
    layout:
      #default
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .         .           ."
        "sidebar  beneden     beneden   thermostaat ."
        "sidebar  overig      familie   media       ."
        "sidebar  footer      footer    footer      ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  beneden     keuken   ."
            ".  thermostaat overig   ."
            ".  media       familie  ."
            ".  footer      footer   ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  beneden   keuken  ."
            "sidebar  thermostaat    overig  ."
            "sidebar  media       familie ."
            "sidebar  footer      footer  ."
            "sidebar  .           .       ."
    cards:
      - type: custom:button-card
        styles: #extra_styles fix
          card:
            - display: none

      #################################################
      #                                               #
      #                    Sidebar                    #
      #                                               #
      #################################################
      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar_template
          - type: grid
            cards:
              # - type: button
              #   icon: custom:roborock-vacuum
              #   tap_action:
              #     !include popup/sidebar_vacuum.yaml
              #   hold_action:
              #     action: none

              - type: button
                icon: mdi:information-outline
                tap_action: !include popup/sidebar_information.yaml
                hold_action:
                  action: none

              - type: button
                icon: mdi:arrow-up-bold-circle-outline
                tap_action: !include popup/sidebar_update.yaml
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.hacs
          # - type: custom:atomic-calendar-revive
          #   showMonth: true
          #   entities:
          #     - entity: calendar.r_offereins_gmail_com
          #       color: orange
          #     - entity: calendar.leny_bosman
          #       color: yellow
          #     - entity: calendar.noa_offereins
          #       color: pink
          #     - entity: calendar.mika_offereins
          #       color: green
          #   name: null
          #   enableModeChange: false
          #   firstDayOfWeek: "1"
          #   showProgressBar: false
          #   showCurrentEventLine: false
          #   howRelativeTime: false
          #   showWeekDay: true
          #   showNoEventsForToday: true
          #   calShowDescription: false
          #   showLastCalendarWeek: false
          #   dateFormat: LL
          #   europeanDate: true
          #   refreshInterval: "300"
          #   showFullDayProgress: false
          #   fullDayEventText: Hele dag
          #   disableEventLink: false
          #   hideFinishedEvents: true
          #   maxDaysToShow: "5"

      #################################################
      #                                               #
      #                   BENEDEN                     #
      #                                               #
      #################################################
      - type: grid
        title: Beneden
        view_layout:
          grid-area: beneden
        columns: 4
        cards:
          - type: custom:button-card
            entity: light.woonkamer_dressoir
            name: Dressoir
            template:
              - light_toggle
              - icon_lamp
          # - type: custom:button-card
          #   entity: light.woonkamer_plafond_sier
          #   name: Plafond
          #   template:
          #     - light_toggle
          #     - icon_lamp
          - type: custom:button-card
            entity: light.woonkamer_wandrek
            name: Wandrek
            template:
              - light_toggle
              - icon_lamp
          - type: custom:button-card
            entity: light.woonkamer_raam_voor
            name: Raam voor
            template:
              - light_toggle
              - icon_lamp
          - type: custom:button-card
            entity: light.woonkamer_raam_zijkant
            name: Raam zij
            template:
              - light_toggle
              - icon_lamp
          - type: custom:button-card
            entity: light.keuken_eettafel
            name: Eettafel
            template:
              - light_no_color
              - icon_hue
          - type: custom:button-card
            entity: media_player.ziggo_beneden
            name: Tv
            state_display: >
              [[[
                if (variables.state == 'playing') {
                  return 'Aan';
                }
              ]]]
            #hold_action: !include popup/vardagsrum_tv.yaml
            template:
              - base
              - icon_tv
              - loader
              #- media
          - type: custom:button-card
            entity: media_player.playstation_4
            name: PS 4
            # hold_action:
            #   !include popup/vardagsrum_playstation.yaml
            template:
              - base
              - media
              - icon_ps5
              - loader

      #################################################
      #                                               #
      #                    Keuken                     #
      #                                               #
      #################################################
      # - type: grid
      #   title: Keuken
      #   view_layout:
      #     grid-area: keuken
      #   columns: 2
      #   cards:
      #     - type: custom:button-card
      #       entity: light.keuken_eettafel
      #       name: Keuken
      #       template:
      #         - light_no_color
      #         - icon_hue

      #################################################
      #                                               #
      #                  THERMOSTAAT                  #
      #                                               #
      #################################################

      - type: grid
        title: ""
        view_layout:
          grid-area: thermostaat
        columns: 1
        cards:
          - type: vertical-stack
            cards:
              # - type: custom:webrtc-camera
              #   entity: camera.voortuin
              #   poster: https://home-assistant.io/images/cast/splash.png
              #   ui: true
              - type: custom:simple-thermostat
                style: |
                  ha-card {
                    --st-font-size-xl: 28px;
                    --st-font-size-m: 14px;
                    --st-font-size-title: 22px;
                    --st-font-size-sensors: 18px;
                    --st-spacing: 2px;
                  }
                entity: climate.thermostaat
                layout:
                  mode:
                    names: true
                    icons: true
                    headings: false
                  step: column
                control:
                  hvac:
                    "off":
                      name: Uit
                      icon: mdi:radiator-disabled
                    heat:
                      name: Aan
                      icon: mdi:radiator
                  preset:
                    away: false
                    none: false
                    activity: false
                    _hide_when_off: true
                    eco:
                      name: Eco
                      icon: mdi:leaf
                    home:
                      name: Normaal
                      icon: mdi:home
                    comfort:
                      name: Comfort
                      icon: mdi:fire
                    sleep: false
                sensors:
                  - entity: climate.thermostaat
                    attribute: hvac_action
                hide:
                  state: true
                header:
                  name: ""
                  icon: false
                step_size: "0.5"
                decimals: "1"
              # - type: entities
              #   card_mod:
              #     class: content
              #   entities:
              #     - entity: sensor.woonkamer_multisensor_humidity
              #       name: Luchtvochtigheid
              # - entity: sensor.woonkamer_multisensor_airpressure
              #   name: Luchtdruk
              # - type: custom:apexcharts-card
              #   layout: minimal
              #   locale: nl-NL
              #   graph_span: 12h
              #   show:
              #     loading: false
              #   apex_config:
              #     plotOptions:
              #       area:
              #         fillTo: end
              #     # grid:
              #     #   padding:
              #     #     top: -15
              #     fill:
              #       type: gradient
              #       gradient:
              #         type: vertical
              #         opacityFrom: 0.8
              #         opacityTo: 0
              #         stops:
              #           - 0
              #           - 99
              #           - 100
              #     stroke:
              #       width: 4
              #     tooltip:
              #       style:
              #         fontSize: 14px
              #       x:
              #         format: dddd HH:mm
              #     chart:
              #       height: 80px
              #     xaxis:
              #       crosshairs:
              #         show: false
              #   series:
              #     - entity: sensor.woonkamer_multisensor_temperature
              #       name: Temp
              #       color: "#385581"
              #       type: area
              #       fill_raw: last
              #       group_by:
              #         func: avg
              #         duration: 1h

      #################################################
      #                                               #
      #                     MEDIA                     #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:
          - type: custom:swipe-card
            start_card: 1
            parameters:
              roundLengths: true
              effect: coverflow
              speed: 650
              spaceBetween: 20
              threshold: 7
              coverflowEffect:
                rotate: 80
                depth: 300
            cards:
              - type: conditional
                conditions:
                  - entity: media_player.ziggo_beneden
                    state_not: "off"
                card:
                  type: custom:button-card
                  entity: media_player.ziggo_beneden
                  template:
                    - conditional_media
                    - icon_apple_tv
              - type: conditional
                conditions:
                  - entity: media_player.keuken_nest_hub
                    state_not: "off"
                card:
                  type: custom:button-card
                  entity: media_player.keuken_nest_hub
                  template:
                    - conditional_media
                    - icon_nest_hub
              - type: conditional
                conditions:
                  - entity: media_player.woonkamer_google_home
                    state_not: "off"
                card:
                  type: custom:button-card
                  entity: media_player.woonkamer_google_home
                  template:
                    - conditional_media
                    - icon_nest_mini
              - type: conditional
                conditions:
                  - entity: media_player.woonkamer_chromecast
                    state_not: "off"
                card:
                  type: custom:button-card
                  entity: media_player.woonkamer_chromecast
                  template:
                    - conditional_media
                    - icon_nest_mini
              - type: grid
                columns: 2
                cards:
                  - type: custom:button-card
                    entity: media_player.woonkamer_chromecast
                    name: Chromecast
                    custom_fields:
                      icon: &icon_chromecast >
                        <svg style="width:24px;height:24px" viewBox="0 0 24 24"><path fill="currentColor" d="M21,3H3C1.89,3 1,3.89 1,5V8H3V5H21V19H14V21H21A2,2 0 0,0 23,19V5C23,3.89 22.1,3 21,3M1,10V12A9,9 0 0,1 10,21H12C12,14.92 7.07,10 1,10M19,7H5V8.63C8.96,9.91 12.09,13.04 13.37,17H19M1,14V16A5,5 0 0,1 6,21H8A7,7 0 0,0 1,14M1,18V21H4A3,3 0 0,0 1,18Z" /></svg>
                    template:
                      - media
                      # - icon_apple_tv

                  - type: custom:button-card
                    name: Home mini
                    entity: media_player.woonkamer_google_home
                    template:
                      - media
                      - icon_nest_mini

                  - type: custom:button-card
                    entity: media_player.spotify_rudolf_offereins
                    name: Spotify
                    template:
                      - media
                      - icon_spotify

                  - type: custom:button-card
                    entity: media_player.keuken
                    name: Keuken Nest hub
                    template:
                      - media
                      - icon_nest_hub

      #################################################
      #                                               #
      #                     Familie                   #
      #                                               #
      #################################################

      - type: grid
        title: Familie
        view_layout:
          grid-area: familie
        columns: 2
        cards:
          - type: custom:button-card
            entity: person.rudolf
            name: Rudolf
            triggers_update:
              - person.rudolf
            tap_action: !include popup/familie_rudolf.yaml
            hold_action:
              action: none
            variables:
              battery: sensor.telefoon_rudolf_battery_level
            template: person

          - type: custom:button-card
            entity: person.leny
            name: Leny
            triggers_update:
              - person.leny
            tap_action: !include popup/familie_leny.yaml
            hold_action:
              action: none
            variables:
              battery: sensor.telefoon_leny_batterijniveau
            template: person
          - type: custom:button-card
            entity: person.noa
            name: Noa
            tap_action: !include popup/familie_noa.yaml
            hold_action:
              action: none
            variables:
              battery: sensor.tablet_noa_batterij
            template: person

          - type: custom:button-card
            entity: person.mika
            name: Mika
            # triggers_update:
            #   - sensor.matte_last_changed
            # tap_action:
            #   !include popup/hemma_mattias.yaml
            hold_action:
              action: none
            variables:
              battery: sensor.tablet_mika_batterijniveau
            template: person

      #################################################
      #                                               #
      #                    OVERIG                     #
      #                                               #
      #################################################

      - type: grid
        title: Overig
        view_layout:
          grid-area: overig
        columns: 2
        cards:
          - type: custom:button-card
            entity: light.overloop_plafond
            name: Overloop
            template:
              - light_toggle
              - icon_spot

          - type: custom:button-card
            entity: light.gang_plafond
            name: Gang
            template:
              - light_toggle
              - icon_spot

          - type: custom:button-card
            entity: light.zolder_plafond
            name: Zolder
            template:
              - light_no_color
              - icon_spot
          - type: custom:button-card
            entity: light.wc_plafond
            name: WC
            template:
              - light_toggle
              - icon_bathroom
      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: custom:button-card
        view_layout:
          grid-area: footer
        template: afval
