################################################
## Automations / Household / Mika Google Meet
################################################
alias: "Mika Google Meet"
trigger:
  - platform: time
    at: "10:15"
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: tts.microsoft_say
    data:
      entity_id: media_player.woonkamer_google_home
      message: 'De Google Meet van Mika begint over 15 minuten.'
  - service: notify.family
    data: 
      title: "Google meet Mika"
      message: "Mika heeft over 15 minuten de Google meet afspraak!"
      data:
        ttl: 0
        priority: high
        



