################################################
## Automations / Voortuin / Achterdeur open in het donker
################################################
alias: Achterdeur open in het donker
description: Wijzig verlichting wanneer achterdeur open gaat
trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_deur
    to: "on"
condition:
  - condition: state
    entity_id: binary_sensor.donker_buiten
    state: "on"
action:
  - service: light.turn_on
    entity_id: light.achtertuin_lantaarnpaal
  - service: light.turn_off
    entity_id: light.voortuin_hek
