################################################
## Automations / Bijkeuken / Verlichting aan
################################################
alias: Bijkeuken verlichting aan
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_bewegingssensor
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    - condition: state
      entity_id: light.bijkeuken_plafond
      state: 'off'
action:
  - service: light.turn_on
    entity_id: light.bijkeuken_plafond
    

