################################################
## Automations / Bijkeuken / Droger bezig
################################################
alias: Droger bezig
initial_state: on
trigger:
  - platform: state
    entity_id: sensor.bijkeuken_droger_huidig_wattage
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.bijkeuken_droger_huidig_wattage
      above: 10
    - condition: state
      entity_id: binary_sensor.bijkeuken_droger
      state: "off"

action:
  - service: input_select.select_option
    entity_id: input_select.bijkeuken_droger_status
    data:
      option: "Bezig"
