################################################
## Automations / Bijkeuken / Droger afronden
################################################
alias: Droger afronden
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.bijkeuken_droger_huidig_wattage
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.bijkeuken_droger_huidig_wattage
      below: 0.75
    - condition: state
      entity_id: input_select.bijkeuken_droger_status
      state: "Bezig"
action:
  - service: input_select.select_option
    entity_id: input_select.bijkeuken_droger_status
    data:
      option: "Afronden"
