alias: Wasmachine klaar
initial_state: on
trigger:
  - platform:  state
    entity_id: input_select.bijkeuken_wasmachine_status
    to: 'Afronden'
    for:
      minutes: 5
condition: 
      condition: state
      entity_id: binary_sensor.bijkeuken_wasmachine
      state: 'off'
action:
  - service: input_select.select_option
    entity_id: input_select.bijkeuken_wasmachine_status
    data:
      option: "Klaar"