alias: Wasmachine bezig
initial_state: on
trigger:
  - platform:  state
    entity_id: sensor.bijkeuken_wasmachine_wattage
  - platform:  homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.bijkeuken_wasmachine_wattage
      above: 10
    - condition: state
      entity_id: binary_sensor.bijkeuken_wasmachine
      state: 'off'
  
action:
  - service: input_select.select_option
    entity_id: input_select.bijkeuken_wasmachine_status
    data:
      option: "Bezig"