################################################
## Automations / Bijkeuken / Wasmachine open
################################################
alias: Wasmachine open
initial_state: on
trigger:
  - platform:  state
    entity_id: binary_sensor.bijkeuken_wasmachine
    to: 'on'
  - platform: homeassistant
    event: start
condition:
  condition: state
  entity_id: binary_sensor.bijkeuken_wasmachine
  state: 'on'
action:
  - service: input_select.select_option
    entity_id: input_select.bijkeuken_wasmachine_status
    data:
      option: "Inactief"