id: 0912e0cd-5bc6-4e42-b27f-e8a365d64ae7
alias: Mika's lamp aan bij beweging
trigger:
  - platform: state
    entity_id: binary_sensor.mika_bewegingssensor
    to: "on"
condition:
  condition: and
  conditions:
    - condition: time
      after: "07:00:00"
      before: "19:30:00"
    - condition: state
      entity_id: binary_sensor.donker_binnen
      state: "on"
action:
  - service: light.turn_on
    entity_id: light.mika_plafond
