alias: Zolder schakelaar
trigger:
- platform: state
  entity_id: binary_sensor.zolder_schakelaar
  from:  
    - 'on'
    - 'off'
  to:  
    - 'on'
    - 'off'
action:
  - service: light.toggle
    data:
      entity_id: light.zolder_plafond