################################################
## Automations / Kleine schuur / Airfryer klaar
################################################
alias: Airfryer klaar
initial_state: on
trigger:
  - platform: state
    entity_id: sensor.kleine_schuur_airfryer_huidig_wattage
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.kleine_schuur_airfryer_status
      state: "Bezig"
    - condition: numeric_state
      entity_id: sensor.kleine_schuur_airfryer_huidig_wattage
      below: 20
action:
  - service: input_select.select_option
    entity_id: input_select.kleine_schuur_airfryer_status
    data:
      option: "Klaar"
  - service: media_player.volume_set
    entity_id: media_player.woonkamer_google_home
    data:
      volume_level: 0.7
  - service: tts.microsoft_say
    data:
      entity_id: media_player.woonkamer_google_home
      message: "De airfryer is klaar!"
  - delay: "00:00:05"
  - service: media_player.volume_set
    entity_id: media_player.woonkamer_google_home
    data:
      volume_level: 0.4
