################################################
## Automations / Kleine schuur / Airfryer bezig
################################################
alias: Airfryer bezig
initial_state: on
trigger:
  - platform: state
    entity_id: sensor.kleine_schuur_airfryer_huidig_wattage
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.kleine_schuur_airfryer_huidig_wattage
      above: 20
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.kleine_schuur_airfryer_status
          state: "Bezig"
action:
  - service: input_select.select_option
    entity_id: input_select.kleine_schuur_airfryer_status
    data:
      option: "Bezig"
