################################################
## Automations / Kleine schuur / Airfryer inactief
################################################
alias: Airfryer inactief
initial_state: on
trigger:
  - platform: state
    entity_id: sensor.kleine_schuur_airfryer_huidig_wattage
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.kleine_schuur_airfryer_huidig_wattage
      above: 0
      below: 20.1
action:
  - service: input_select.select_option
    entity_id: input_select.kleine_schuur_airfryer_status
    data:
      option: "Inactief"
