alias: Airfryer klaar
initial_state: on
trigger:
  - platform:  state
    entity_id: sensor.kleine_schuur_airfryer_wattage
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.kleine_schuur_airfryer_status
      state:  'Bezig'
    - condition: numeric_state
      entity_id: sensor.kleine_schuur_airfryer_wattage
      below: 20  
action:
  - service: input_select.select_option
    entity_id: input_select.kleine_schuur_airfryer_status
    data:
      option: "Klaar"
  - service: media_player.volume_set
    entity_id: media_player.woonkamer_google_home
    data:
      volume_level: 1
  - service: tts.google_translate_say
    entity_id: media_player.woonkamer_google_home
    data:
      message: 'De airfryer is klaar!'
      language: 'nl'
  - delay: '00:00:03'
  - service: media_player.volume_set
    entity_id: media_player.woonkamer_google_home
    data:
      volume_level: 0.4