################################################
## Automations / Kleine schuur / Diepvries open
################################################
alias: Diepvries open
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.kleine_schuur_diepvries
    to: 'on'
    for: 
      minutes: 2
action:
  - service: notify.family
    data: 
      title: "De diepvries staat open"
      message: "Ga hem gauw dichtdoen"
  - service: media_player.volume_set
    entity_id: media_player.woonkamer_google_home
    data:
      volume_level: 0.7
  - service: tts.microsoft_say
    data:
      entity_id: media_player.woonkamer_google_home
      message: 'De diepvries staat nog open!'
  - delay: '00:00:03'
  - service: media_player.volume_set
    entity_id: media_player.woonkamer_google_home
    data:
      volume_level: 0.4
      

