################################################
## Automations / Achtertun / Verlichting aan
################################################
alias: Achtertuinverlichting aan
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.bijkeuken_deur
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    - condition: state
      entity_id: light.achtertuin_paal_en_ornament
      state: 'off'
action:
  - service: light.turn_on
    entity_id: light.achtertuin_paal_en_ornament
  - delay: '00:02:00'
  - service: light.turn_off
    entity_id: light.achtertuin_paal_en_ornament
