################################################
## Automations / Achtertuin / Verlichting aan
################################################
alias: Achtertuinverlichting aan
initial_state: on
trigger:
  - platform: time
    at: "07:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.donker_buiten
    state: "on"
action:
  - service: light.turn_on
    entity_id: light.achtertuin_paal_en_ornament
