alias: WC verlichting aan
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.wc_bewegingssensor
    from: 'off'
    to: 'on'
action:
  - service: light.turn_on
    entity_id: light.wc_plafond

