alias: Motion lights
trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_bewegingssensor
    to: 'on'
condition:
    - condition: state
      entity_id: binary_sensor.donker_binnen
      state: 'on'
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: time
      after: '7:00:00'
      before: '23:00:00'
action:
    - service: light.turn_on
      data:
        entity_id: light.woonkamer