alias: No Motion lights
trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_bewegingssensor
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.donker_binnen
    to: 'off'
  - platform: state
    entity_id: media_player.ziggobeneden
    to: 'off'
    for:
      minutes: 10
condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.woonkamer
      state: 'on'
    - condition: state
      entity_id: media_player.ziggobeneden
      state: 'off'
    - condition: state
      entity_id: binary_sensor.woonkamer_bewegingssensor
      state: 'off'
action:
    - service: light.turn_off
      data:
        entity_id: light.woonkamer