################################################
## Automations / Woonkamer / Lampen uit beweging
################################################
alias: No Motion lights
trigger:
  - platform: state
    entity_id: binary_sensor.donker_binnen
    to: "off"
condition:
  - condition: state
    entity_id: light.woonkamer
    state: "on"
action:
  - service: light.turn_off
    data:
      entity_id: light.woonkamer
