alias: Speel radio stream
initial_state: on
trigger:
  - platform: state
    entity_id: input_text.radio_channel
action:
  - service: media_player.play_media
    data_template:
      entity_id: media_player.woonkamer_google_home
      media_content_id: '{{states.input_text.radio_channel.state}}'
      media_content_type: channel