################################################
## Automations / Voortuin / Achterdeur Open in het donker
################################################
alias: Achterdeur open in het donker
trigger:
  platform: state
  entity_id: binary_sensor.bijkeuken_deur
  to: 'off'
condition:
  condition: state
  entity_id: binary_sensor.donker_buiten
  state: 'on'
action:
  - service: light.turn_off
    entity_id: light.voortuin_hek
  - delay:
      minutes: 10
  - service: light.turn_on
    entity_id: light.voortuin_hek
  
