################################################
## Automations / Voortuin / Achterdeur Open in het donker
################################################
alias: Achterdeur open in het donker
trigger:
  platform: state
  entity_id: binary_sensor.bijkeuken_deur
  to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.donker_buiten
  state: 'on'
action:
  - service: script.dim_hek_vertrek_in_donker
  - service: script.achtertuin_aan_bij_open_deur
  
