################################################
## Automations / Voortuin / Bel gaat
################################################
alias: Bel gaat
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.gang_deurbel_button
    to: 'on'
  - platform: state
    entity_id: binary_sensor.gang_deurbel_rf_knop
    to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.foscam_camera
      filename: "/media/snapshots/snapshot.jpg"
  - service: notify.family
    data_template: 
      message: "Er staat iemand aan de voordeur"
      title: "De bel gaat"
      data: 
        image: /media/local/snapshots/snapshot.jpg
        ttl: 0
        priority: high
        channel: alarm_stream
  - service: light.turn_on
    entity_id: light.wall_tablet_screen
  - service: browser_mod.popup
    data:
      title: Voordeur
      card:
        type: picture-glance
        camera_image: camera.foscam_camera
        camera_view: live
        entities: []
      deviceID:
        - wall-tablet