###################################################
## Automations / Voortuin / Verlichting hek
###################################################
alias: Voortuin verlichting 's nachts
description: "'Wanneer het donker is, lampen hek na 10 minuten weer aan."
trigger:
  - platform: state
    entity_id: light.voortuin_hek
    to: "off"
    for:
      minutes: 10
condition:
  - condition: state
    entity_id: binary_sensor.donker_buiten
    state: "on"
action:
  - service: light.turn_on
    entity_id: light.voortuin_hek
