################################################
## Automations / Noa / Reset pufje
################################################
alias: Reset pufje Noa
initial_state: on
trigger:
  - platform: time
    at: "6:00:00"
  - platform: time
    at: "18:00:00"
action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.noa_pufje_genomen