################################################
## Automations / System / beweging schuur auto off
################################################
alias: Auto off Beweging schuur
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.kleine_schuur_bewegingssensor
    to: 'on'
    for:
      seconds: 5
action:
  - service: mqtt.publish
    data:
      topic: 'rf_schuur/tele/RESULT'
      payload: "{
                  \"RfReceived\":{
                    \"Data\":\"D2242E-off\"
                  }
                }"