################################################
## Automations / System / Select theme
################################################
alias: Select theme
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.themes

action:
  - service: frontend.set_theme
    data_template:
      name: "{{ states('input_select.themes') }}"