"""Constants for the Ziggo Mediabox Next integration."""
ZIGGO_API = "ziggo_api"
CONF_COUNTRY_CODE = "country_code"
CONF_OMIT_CHANNEL_QUALITY = "omit_channel_quality"
CONF_REMOTE_KEY = "remote_key"

RECORD = "record"
REWIND = "rewind"
FAST_FORWARD = "fast_forward"
REMOTE_KEY_PRESS = "remote_key_press"