### Basic setup for all devices

# Enable logging
logger:

# Enable Home Assistant API
api:

# allow OTA flashing
ota:

#Run a webserver
web_server:
  port: 80

# Wifi
wifi:
  ssid: !secret default_wifi_ssid
  password: !secret default_wifi_password
  ap:
    ssid: "${device_name}_ap"

# sensor:      
#   # Extra sensor to keep track of plug uptime
#   - platform: uptime
#     name: ${device_name} Uptime
#   # WiFi Signal sensor.
#   - platform: wifi_signal
#     name: ${device_name} Wifi Signal Strength
#     update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: status
    name: "${device_name} State"

# text_sensor:
#   - platform: version
#     name: "${device_name} ESPHome Version"
#   - platform: wifi_info
#     ip_address:
#       name: ${device_name} IP
#     ssid:
#       name: ${device_name} SSID

# switch:
#   # Switch to restart the device.
#   - platform: restart
#     name: Restart ${device_name}