<<: !include base.yaml

esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m

switch:
  - platform: gpio
    pin:
      number: 0
      inverted: yes
    id: "${device_name}_relay"
    name: "${device_name} Relay"