<<: !include base.yaml

esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m

#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgbw
    id: ${device_name}_light
    name: "${device_name} Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w