<<: !include base.yaml
esphome:
  name: $device_name
  platform: ESP8266
  board: esp8285
  
binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_name} Button"
    on_press:
      - light.toggle: "${device_name}_light"
    internal: true

output:
  - platform: gpio
    id: gpio_12
    pin: 12
  - platform: gpio
    id: gpio_4
    pin: 4
    inverted: true

light:  
  - platform: binary
    name: "${device_name}"
    output: gpio_12
    id: "${device_name}_light"
    #on_turn_on:
    #  - light.toggle: "${device_name}_button"
    #on_turn_off:
    #  - light.toggle: "${device_name}_button"
  - platform: binary
    name: "${device_name} button"
    output: gpio_4
    id: "${device_name}_button"
    internal: true