<<: !include base.yaml
esphome:
  name: $device_name
  platform: ESP8266
  board: esp8285
  
binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_name} Button"
    on_press:
      - switch.toggle: "${device_name}_relay"

switch:
  - platform: gpio
    id: "${device_name}_led"
    pin:
      number: GPIO4
      inverted: true
    internal: true

  - platform: gpio
    name: "${device_name}"
    icon: "mdi:power-plug"
    pin: GPIO12
    id: "${device_name}_relay"
    on_turn_on:
      - switch.turn_on: "${device_name}_led"
    on_turn_off:
      - switch.turn_off: "${device_name}_led"