<<: !include base.yaml

esphome:
  name: $device_name
  platform: ESP8266
  board: esp8285

switch:
  - platform: gpio
    pin:
      number: 4
    id: "${device_name}_relay"
    name: "${device_name}"
    restore_mode: $restore_mode