<<: !include shelly_1_base.yaml


output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    name: "${device_name} Light"
    output: gpio_4
    id: "${device_name}_light"
    
