<<: !include base.yaml

esphome:
  name: $device_name
  platform: ESP8266
  board: esp8285

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "${device_name} Switch"
    on_state:
      - light.toggle: "${device_name}_light"
    internal: true