<<: !include base.yaml

esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m

# Sensor for button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name} Button"
    on_press:
      then:
        - light.toggle: ${device_name}_light
  
output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True
    
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${device_name} Button Led"
    output: blue_led
  - platform: binary
    id: ${device_name}_light
    name: "${device_name} Light"
    output: relay