---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#
ota:
  id: component_ota
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
