---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#
ota:
  - id: component_ota_esphome
    platform: esphome
  - id: component_ota_webserver
    platform: web_server
