---
# Restart
#
# A simple switch to restart the ESP device.
# I wish there was a single service for this,
# by default...
#
# https://esphome.io/components/switch/restart.html
#
button:
  - <<: !include ../buttons/restart.yaml
