---
# Web Server component
#
# The web_server component creates a simple web server on the node that can be
# accessed through any browser and a simple REST API. Please note that enabling
# this component will take up a lot of memory and can lead to problems,
# especially on the ESP8266.
#
# https://esphome.io/components/web_server.html
#
web_server:
  id: component_web_server
