---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

wifi:
  id: component_wifi
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  reboot_timeout: 10min
  ap:
    ssid: "${name}"
  manual_ip:
    static_ip: "${wifi_static_ip}"
    gateway: 192.168.1.1
    subnet: 255.255.255.0

sensor:
  - <<: !include ../sensors/wifi_signal_percentage.yaml
  - <<: !include ../sensors/wifi_signal.yaml
    on_value:
      - component.update: sensor_wifi_signal_percentage

text_sensor:
  - <<: !include ../text_sensors/wifi_info.yaml
