################################################
## Automations / Noa / Rotate left
################################################
alias: Noa bed draait links
mode: single
description: ''
trigger:
- device_id: 73bede253078469e973c7a521c7395bf
  domain: deconz
  platform: device
  type: remote_button_rotated
  subtype: left
condition:
  - condition: device
    type: is_on
    device_id: cda7501a0b9811ebac43cb81d1a09be0
    entity_id: light.noa_bed
    domain: light
action:
- type: brightness_increase
  device_id: cda7501a0b9811ebac43cb81d1a09be0
  entity_id: light.noa_bed
  domain: light

