################################################
## Automations / Noa / Symfonisk Double click
################################################
alias: Noa bed twee keer drukken
mode: single
trigger:
  - device_id: 73bede253078469e973c7a521c7395bf
    domain: deconz
    platform: device
    type: remote_button_double_press
    subtype: turn_on
action:
  - service: input_select.select_next
    entity_id: input_select.noa_bed_effects

