alias: Noa bed drie keer drukken
mode: single
trigger:
- device_id: 73bede253078469e973c7a521c7395bf
  domain: deconz
  platform: device
  type: remote_button_triple_press
  subtype: turn_on
condition: []
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.noa_bed_effects
      option: Solid
  - service: light.turn_on
    data:
      entity_id: light.noa_bed
      brightness_pct: 10
      color_name: white


