################################################
## Automations / Household /Noa Google Meet
################################################
alias: "Noa Google Meet"
trigger:
  - platform: time
    at: "08:45"
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: tts.microsoft_say
    data:
      entity_id: media_player.woonkamer_google_home
      message: 'De Google Meet van Noa begint over 15 minuten.'
  - service: notify.family
    data: 
      title: "Google meet Noa"
      message: "Noa heeft over 15 minuten de Google meet afspraak!"
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
        



