packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp01s.yaml
switch:
  - platform: gpio
    pin:
      number: 0
      inverted: true
    id: "${slug}_relay"
    restore_mode: $restore_mode

button:
  - platform: template
    name: "${name}"
    on_press:
      - switch.turn_on: "${slug}_relay"
      - delay: $toggle_delay
      - switch.turn_off: "${slug}_relay"
