packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp01s.yaml

switch:
  - platform: gpio
    pin:
      number: 0
      inverted: yes
    id: "${slug}_relay"
    name: "${name}"
    restore_mode: $restore_mode
