packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp01s.yaml
switch:
  - platform: gpio
    internal: true
    pin:
      number: 0
      inverted: true
    id: "${id}_relay"
    restore_mode: $restore_mode

button:
  - platform: template
    name: "${name}"
    id: "${id}_button"
    on_press:
      - switch.turn_on: "${id}_relay"
      - delay: $toggle_delay
      - switch.turn_off: "${id}_relay"
    device_id: "${id}_device"
