---
# Device: Neo Coolcam (switch)
#
packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    name: "${name} button"
    on_press:
      - switch.toggle: "${id}_relay"
    internal: true

switch:
  - platform: gpio
    id: "${id}_led"
    pin:
      number: GPIO4
      inverted: true
    internal: true

  - platform: gpio
    name: "${name}"
    icon: "mdi:power-plug"
    pin: GPIO12
    id: "${id}_relay"
    on_turn_on:
      - switch.turn_on: "${id}_led"
    on_turn_off:
      - switch.turn_off: "${id}_led"
    device_id: "${id}_device"
