---
# Device: Neo Coolcam (light)
#
packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: true
    name: "${name} button"
    on_press:
      - light.toggle: "${id}_light"
    internal: true

output:
  - platform: gpio
    id: gpio_12
    pin: 12
  - platform: gpio
    id: gpio_4
    pin: 4
    inverted: true

light:
  - platform: binary
    name: "${name}"
    output: gpio_12
    id: "${id}_light"
    device_id: "${id}_device"
  - platform: binary
    name: "${name} button"
    output: gpio_4
    id: "${id}_button"
    internal: true
