---
# Device: Neo Coolcam PM (light)
#
packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "${name} button"
    on_press:
      - light.toggle: "${slug}_light"
    internal: true

output:
  - platform: gpio
    id: gpio_14
    pin: 14

light:
  - platform: binary
    name: "${name}"
    output: gpio_14
    id: "${slug}_light"

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${name} Amperage"
      unit_of_measurement: A
    voltage:
      name: "${name} Voltage"
      unit_of_measurement: V
    power:
      name: "${name} Wattage"
      unit_of_measurement: W
      id: "${slug}_wattage"
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${name} Total Daily Energy"
    power_id: "${slug}_wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
