packages:
  <<: !include_dir_named ../common
  board: !include ../boards/rfbridge.yaml

esphome:
  on_boot:
    then:
      - rf_bridge.start_advanced_sniffing

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200

logger:
  baud_rate: 0

rf_bridge:
  on_advanced_code_received:
    - homeassistant.event:
        event: esphome.rf_advanced_code_received
        data:
          length: !lambda "char buffer [10];return itoa(data.length,buffer,16);"
          protocol: !lambda "char buffer [10];return itoa(data.protocol,buffer,16);"
          code: !lambda "return data.code;"
    - logger.log: "Code received!"
