packages:
  <<: !include_dir_named ../common
  board: !include ../boards/wemos-d1-mini.yaml

i2c:
  sda: D1
  scl: D2

sensor:
  - platform: bme280
    temperature:
      name: "${name} Temperature"
      oversampling: 16x
      device_id: "${id}_device"
    pressure:
      name: "${name} Pressure"
      device_id: "${id}_device"
    humidity:
      name: "${name} Humidity"
      device_id: "${id}_device"
    address: 0x76
    update_interval: 60s
