# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoDecoders/LocationReportsUpload.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# Import Common_pb2 first to ensure it's loaded before we create our descriptor
from custom_components.googlefindmy.ProtoDecoders import Common_pb2 as ProtoDecoders_dot_Common__pb2

# Use the same descriptor pool as Common_pb2 to maintain dependencies
try:
    # Try to access Common's descriptor pool
    _findmy_pool = ProtoDecoders_dot_Common__pb2._common_pool
except AttributeError:
    # Fallback to creating our own pool if Common doesn't have _common_pool
    _findmy_pool = _descriptor_pool.DescriptorPool()

DESCRIPTOR = _findmy_pool.AddSerializedFile(b'\n)ProtoDecoders/LocationReportsUpload.proto\x1a\x1aProtoDecoders/Common.proto\"|\n\x15LocationReportsUpload\x12\x18\n\x07reports\x18\x01 \x03(\x0b\x32\x07.Report\x12\'\n\x0e\x63lientMetadata\x18\x02 \x01(\x0b\x32\x0f.ClientMetadata\x12\x0f\n\x07random1\x18\x03 \x01(\x04\x12\x0f\n\x07random2\x18\x04 \x01(\x04\"g\n\x06Report\x12%\n\radvertisement\x18\x01 \x01(\x0b\x32\x0e.Advertisement\x12\x13\n\x04time\x18\x04 \x01(\x0b\x32\x05.Time\x12!\n\x08location\x18\x06 \x01(\x0b\x32\x0f.LocationReport\"U\n\rAdvertisement\x12\x1f\n\nidentifier\x18\x05 \x01(\x0b\x32\x0b.Identifier\x12#\n\x1bunwantedTrackingModeEnabled\x18\x06 \x01(\r\";\n\nIdentifier\x12\x14\n\x0ctruncatedEid\x18\x06 \x01(\x0c\x12\x17\n\x0f\x63\x61nonicDeviceId\x18\x07 \x01(\x0c\"<\n\x0e\x43lientMetadata\x12*\n\x07version\x18\x02 \x01(\x0b\x32\x19.ClientVersionInformation\"7\n\x18\x43lientVersionInformation\x12\x1b\n\x13playServicesVersion\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoDecoders.LocationReportsUpload_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCATIONREPORTSUPLOAD']._serialized_start=73
  _globals['_LOCATIONREPORTSUPLOAD']._serialized_end=197
  _globals['_REPORT']._serialized_start=199
  _globals['_REPORT']._serialized_end=302
  _globals['_ADVERTISEMENT']._serialized_start=304
  _globals['_ADVERTISEMENT']._serialized_end=389
  _globals['_IDENTIFIER']._serialized_start=391
  _globals['_IDENTIFIER']._serialized_end=450
  _globals['_CLIENTMETADATA']._serialized_start=452
  _globals['_CLIENTMETADATA']._serialized_end=512
  _globals['_CLIENTVERSIONINFORMATION']._serialized_start=514
  _globals['_CLIENTVERSIONINFORMATION']._serialized_end=569
# @@protoc_insertion_point(module_scope)
