// custom_components/googlefindmy/ProtoDecoders/RpcStatus.proto
//
// Vendored google.rpc.Status definition.
// Reference: https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto
//
// This is a local copy to avoid depending on googleapis-common-protos.
// google.protobuf.Any is imported from the official protobuf package.

syntax = "proto3";

package google.rpc;

import "google/protobuf/any.proto";

// The `Status` type defines a logical error model that is suitable for
// different programming environments, including REST APIs and RPC APIs.
// It is used by [gRPC](https://github.com/grpc).
message Status {
  // The status code, which should be an enum value of [google.rpc.Code].
  // For HTTP, this maps to the HTTP status code.
  int32 code = 1;

  // A developer-facing error message, which should be in English.
  // Any user-facing error message should be localized.
  string message = 2;

  // A list of messages that carry the error details. There is a common set of
  // message types for APIs to use. E.g., DebugInfo, QuotaFailure, BadRequest.
  repeated google.protobuf.Any details = 3;
}
