# ruff: noqa: E501, E712, I001, UP009, F821, E402, F401
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProtoDecoders/RpcStatus.proto
# Re-serialized to reference the official google/protobuf/any.proto
# instead of a vendored copy (the vendored Any_pb2 was identical to the
# official google.protobuf.any_pb2 and caused a duplicate-symbol crash
# on Python >= 3.13 when another integration loaded the official library).
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import any_pb2 as _official_any_pb2
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RpcStatus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# Use a separate descriptor pool so that google.rpc.Status does not collide
# with googleapis-common-protos if another integration installs that package.
# Seed the pool with the official google/protobuf/any.proto so the
# dependency on google.protobuf.Any resolves correctly.
_rpc_pool = _descriptor_pool.DescriptorPool()
_rpc_pool.AddSerializedFile(_official_any_pb2.DESCRIPTOR.serialized_pb)

DESCRIPTOR = _rpc_pool.AddSerializedFile(b'\n\x0fRpcStatus.proto\x12\ngoogle.rpc\x1a\x19google/protobuf/any.proto\"N\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoDecoders.RpcStatus_pb2', globals())
if not _descriptor._USE_C_DESCRIPTORS:

  DESCRIPTOR._loaded_options = None
  _STATUS._serialized_start=58
  _STATUS._serialized_end=136
# @@protoc_insertion_point(module_scope)
