################################################
## Automations / Household / Notificatie afval
################################################
alias: Afval
initial_state: on
trigger:
  - platform: time
    at: "17:00:00"
condition:
  condition: not
  conditions:
    - condition: state
      entity_id: sensor.afvalinfo_tomorrow
      state: 'none'
action:
  - service: notify.family
    data_template: 
      title: "Morgen is een afvaldag"
      message: "Opgehaalde afval: {{ states.sensor.afvalinfo_tomorrow.state }}"