################################################
## Automations / Bijkeuken / Droger uit
################################################
alias: Droger uit
trigger:
  platform: event
  event_type: mobile_app_notification_action
  event_data:
    action: turn_on_guest_mode
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.gast_modus
