alias: "Laatste gaat naar bed"
initial_state: on
trigger:
  - platform: state
    entity_id: input_boolean.nachtmode
    from: "off"
    to: "on"
action:
  - service: script.turn_on
    target:
      entity_id: script.last_sleeper
