alias: Nachtverlichting uit
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.donker_buiten
    to: 'off'
action:
  - service: light.turn_off
    entity_id: light.buitenverlichting
