################################################
## Automations / Household / Nachtverlichting aan
################################################
alias: Nachtverlichting aan
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.donker_buiten
    to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.donker_buiten
  state: 'on'
action:
  - service: light.turn_on
    entity_id: light.buitenverlichting
