################################################
## Automations / Household / Nachtverlichting buiten
################################################
alias: Nachtverlichting buiten
description: "Handle night lights based on illumination"
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.donker_buiten
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.donker_buiten
            state: "on"
        sequence:
          - service: light.turn_on
            entity_id: light.buitenverlichting
      - conditions:
          - condition: state
            entity_id: binary_sensor.donker_buiten
            state: "off"
        sequence:
          - service: light.turn_off
            entity_id: light.buitenverlichting
