################################################
## Automations / Bijkeuken / Thermostaat uit
################################################
alias: Thermostaat uit
trigger:
  platform: event
  event_type: mobile_app_notification_action
  event_data:
    action: turn_off_thermostat
action:
  - service: climate.set_preset_mode
    data:
      entity_id: climate.thermostaat
      preset_mode: away
