substitutions:
  label: esp21
  slug: achtertuin_druppelslang
  name: Achtertuin Druppelslang
  description: Bedient de druppelslang in de achtertuin.
  restore_mode: ALWAYS_OFF
  wifi_static_ip: 192.168.1.203

packages:
  <<: !include_dir_named ./common
  board: !include ./boards/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "${name}"
    on_state:
      - switch.toggle: "${slug}_relay"
    internal: true

switch:
  - platform: gpio
    pin:
      number: 4
    id: "${slug}_relay"
    name: "${name}"
    restore_mode: $restore_mode
    on_turn_on:
      - delay: 6h
      - switch.turn_off: "${slug}_relay"