substitutions:
  label: esp06
  slug: bijkeuken_plafond
  name: Bijkeuken Plafond
  description: Bedient de lamp in de bijkeuken.
  restore_mode: RESTORE_DEFAULT_OFF
  wifi_static_ip: 192.168.1.84

packages:
  device: !include devices/shelly1_light.yaml