substitutions:
  label: esp03
  slug: bijkeuken_wasmachine
  name: Bijkeuken Wasmachine
  description: Monitort energieverbruik wasmachine.
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "800"
  restore_mode: RESTORE_DEFAULT_ON

packages:
  device: !include devices/neo_coolcam_pm.yaml

