#coolcam vensterbank
<<: !include _templates/neo_coolcam_pm.yaml
substitutions:
  device_name: esp04
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "800"
  restore_mode: RESTORE_DEFAULT_OFF