#shelly_1_voortuin_sproeier
<<: !include _templates/shelly_1_switch.yaml
substitutions:
  device_name: esp17
  restore_mode: ALWAYS_OFF
  
switch:
  - platform: gpio
    pin:
      number: 4
    id: "${device_name}_relay"
    name: "${device_name}"
    restore_mode: $restore_mode
    on_turn_on:
      - delay: 1h
      - switch.turn_off: ${device_name}_relay