#esp garagedeur

<<: !include _templates/base.yaml
substitutions:
  device_name: esp12

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

switch:
  - platform: gpio
    pin:
      number: 0
      inverted: yes
    id: "${device_name}_relay"

cover:
  - platform: template
    device_class: door
    name: "${device_name}_cover"
    open_action:
      - switch.turn_off: ${device_name}_relay
      - switch.turn_on: ${device_name}_relay
      - delay: 0.1s
      - switch.turn_off: ${device_name}_relay
    close_action:
      - switch.turn_off: ${device_name}_relay
      - switch.turn_on: ${device_name}_relay
      - delay: 0.1s
      - switch.turn_off: ${device_name}_relay
    stop_action:
      - switch.turn_off: ${device_name}_relay
      - switch.turn_on: ${device_name}_relay
      - delay: 0.1s
      - switch.turn_off: ${device_name}_relay
    optimistic: true
    assumed_state: true