<<: !include _templates/base.yaml
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

substitutions:
  device_name: esp21

# binary_sensor:
#   - platform: gpio
#     pin:
#       number: D2
#       mode: INPUT_PULLUP
#       inverted: true
#     name: "${device_name} Button"

# switch:
#   - platform: gpio
#     pin:
#       number: D1
#       inverted: yes
#     id: "${device_name}_relay"
#     name: "${device_name}"

# sensor:
#   - platform: ultrasonic
#     trigger_pin: D7
#     echo_pin: D8
#     update_interval: 5s
#     name: "Ultrasonic Sensor"

sensor:
  - platform: adc
    pin: A0
    name: "Living Room Brightness"
    update_interval: 10s
    filters:
      - multiply: 3300
    