#esp32 mcu
<<: !include _templates/base.yaml
esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s

substitutions:
  device_name: esp24

i2c:
  sda: GPIO21
  scl: GPIO22

# display:
#   - platform: ssd1306_i2c
#     model: "SSD1306 128x64"
#     reset_pin: GPIO0
#     address: 0x3C
#     lambda: |-
#       it.printf(0, 0, id(my_font), "Het is : %.1f graden", id(temp).state);
#       it.printf(0, 12, id(my_font), "Luchtdruk is : %.1f ", id(pres).state);
#       it.printf(0, 24, id(my_font), "Vochtigheid s : %.1f ", id(hum).state);
# font:
#   - file: "_fonts/comic-sans-ms/comici.ttf"
#     id: my_font
#     size: 12
    
# esp32_ble_beacon:
#   type: iBeacon
#   uuid: '11cdec06-964c-018d-8495-b4570b8be4a4'

sensor:
  - platform: bmp280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
      id: temp
      internal: false
    pressure:
      name: "BME280 Pressure"
      id: pres
      internal: false
    # humidity:
    #   name: "BME280 Humidity"
    #   id: hum
    #   internal: false
    address: 0x77
    update_interval: 60s
