<<: !include _templates/base.yaml
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

substitutions:
  device_name: esp21

i2c:
  sda: D2
  scl: D1

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    