<<: !include ./_templates/base.yaml
esphome:
  name: esp29
  platform: ESP8266
  board: d1_mini

font:
  - file: ./_fonts/comic-sans-ms/ComicSansMS3.ttf
    id: font1
    size: 12

i2c:
  sda: D2
  scl: D1

sensor:
  - platform: bme280
    temperature:
      id: temperature
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      id: pressure
      name: "BME280 Pressure"
    humidity:
      id: humidity
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 60s

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.printf(0, 5, id(font1),  "Temperat. : %.1f°C",id(temperature).state);
      it.printf(0, 25, id(font1), "Pressure   : %.1fhP",id(pressure).state);
      it.printf(0, 45, id(font1), "Humidity   : %.1f%%",id(humidity).state);