substitutions:
  label: esp27
  id: garage_werkbank
  name: Garage Werkbank
  description: Lamp boven de werkbank in de garage.
  wifi_static_ip: 192.168.1.133
packages:
  device: !include devices/shelly1_light.yaml