substitutions:
  label: esp27
  slug: garage-werkbank
  id: garage_werkbank
  name: Garage Werkbank
  description: Lamp boven de werkbank in de garage.
  wifi_static_ip: 192.168.1.49

packages:
  device: !include devices/shelly1_light.yaml