# failes update
substitutions:
  label: esp11
  slug: garage_garagedeur
  name: Garage Garagedeur
  description: Schakelt de garagedeur.
  restore_mode: ALWAYS_OFF
  toggle_delay: 1500ms
  wifi_static_ip: 192.168.1.121
  
packages:
    device: !include devices/esp01s-relay-off.yaml
