substitutions:
  label: esp19
  id: kleine_schuur_airfryer
  name: Kleine schuur Airfryer
  description: Monitort energieverbruik airfryer.
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "800"
  restore_mode: RESTORE_DEFAULT_OFF
  wifi_static_ip: 192.168.1.186

packages:
  device: !include devices/neo_coolcam_pm.yaml