# Is in fact a Sonoff T4 (no neutral)
substitutions:
  label: esp15
  slug: mika_plafond
  name: Mika Plafond
  description: Bedient de lamp in Mika's slaapkamer.
  restore_mode: RESTORE_DEFAULT_OFF
  wifi_static_ip: 192.168.1.103
packages:
  device: !include devices/sonoff_t1_light.yaml