substitutions:
  label: esp13
  slug: noa-plafond
  id: noa_plafond
  name: Noa Plafond
  description: Bedient de lamp in Noa's slaapkamer.
  restore_mode: RESTORE_DEFAULT_OFF
  wifi_static_ip: 192.168.1.107
packages:
  device: !include devices/sonoff_t1_light.yaml