substitutions:
  label: esp23
  id: overloop_plafond
  name: Overloop Plafond
  description: Bedient de lamp op de overloop.
  restore_mode: RESTORE_DEFAULT_OFF
  wifi_static_ip: 192.168.1.223

packages:
  device: !include devices/shelly1_light.yaml