substitutions:
  label: esp14
  slug: slaapkamer_plafond
  name: Slaapkamer Plafond
  description: Bedient de lamp in de slaapkamer.
  restore_mode: RESTORE_DEFAULT_OFF
packages:
  device: !include devices/sonoff_t1_light.yaml