substitutions:
  label: esp17
  slug: voortuin_sproeier
  name: Voortuin Sproeier
  description: Bedient de sproeier in de voortuin.
  restore_mode: ALWAYS_OFF
  wifi_static_ip: 192.168.1.181

packages:
  device: !include devices/shelly1.yaml