substitutions:
  label: esp07
  slug: wc_plafond
  name: WC Plafond
  description: Bedient de lamp in de wc.
  restore_mode: RESTORE_DEFAULT_OFF
  wifi_static_ip: 192.168.1.70

packages:
  device: !include devices/shelly1_light.yaml