substitutions:
  label: esp01
  slug: woonkamer_dressoir
  name: Woonkamer Dressoir
  description: Bedient het licht op het dressoir in de woonkamer.

packages:
  device: !include devices/neo_coolcam_light.yaml