substitutions:
  label: esp05
  id: woonkamer_raam_voor
  name: Woonkamer Raam Voor
  description: Bedient het licht in het raam voor.
  wifi_static_ip: 192.168.1.250

packages:
  device: !include devices/neo_coolcam_light.yaml