substitutions:
  label: esp04
  id: woonkamer_raam_zijkant
  name: Woonkamer Raam zijkant
  description: Bedient de lamp in het zijraam.
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "800"
  restore_mode: RESTORE_DEFAULT_OFF
  wifi_static_ip: 192.168.1.245

packages:
  device: !include devices/neo_coolcam_pm_light.yaml