substitutions:
  label: esp28
  slug: zolder_cv_ketel
  name: Zolder CV ketel
  description: Schakelt de CV ketel.
  restore_mode: RESTORE_DEFAULT_OFF

packages:
  device: !include devices/esp01s-relay.yaml