substitutions:
  label: esp02
  name: Zolder Buetooth proxy
  description: Bluetooth proxy voor zolder
packages:
  device: !include devices/esp-wroom-32.yaml
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true