substitutions:
  label: esp02
  slug: zolder_voeding_tablet
  name: Zolder Voeding tablet
  description: Schakelt de voeding van de muur tablet.
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "800"
  restore_mode: RESTORE_DEFAULT_ON
  wifi_static_ip: 192.168.1.60

packages:
  device: !include devices/neo_coolcam_pm.yaml